CREATE TABLE "Application" (
    "id" TEXT NOT NULL PRIMARY KEY DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-' || '4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random()) % 4 + 1,1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
    "timestamp" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "fullName" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "careerMilestones" TEXT,
    "careerTurningPoints" TEXT,
    "ventureVision" TEXT,
    "ventureGoals" TEXT,
    "industryFocus" TEXT,
    "targetAudience" TEXT,
    "audienceDemographics" TEXT,
    "audiencePainPoints" TEXT,
    "audienceAge" TEXT,
    "differentiation" TEXT,
    "uniqueValue" TEXT,
    "competitors" TEXT,
    "brandImage" TEXT,
    "admiredInfluencers" TEXT,
    "brandAesthetics" TEXT,
    "brandEmotions" TEXT,
    "brandPersonality" TEXT,
    "brandFontPreference" TEXT,
    "scalingGoals" TEXT,
    "growthStrategies" TEXT,
    "longTermVision" TEXT,
    "additionalInfo" TEXT,
    "keyDeadlines" TEXT,
    "discoveryChannels" TEXT,
    "audienceGender" TEXT,
    "audienceMaritalStatus" TEXT,
    "brandValues" TEXT,
    "submittedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX "Application_email_idx" ON "Application"("email");
